name: Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_versions: ["3.11"]

    steps:
      - uses: action/checkout@v3
      - name: Set up Python ${{ matrix.python-version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }
      - name: Display version
        run: |
          python -c "import sys; print(sys.version)"
      - name: Install depends
        run: python3 -m pip install --upgrade build
      - name: Build archive
        run: |
          mkdir -p artefacts
          python3 -m build --outdir artefacts/
