name: Checks

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:

      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display version
        run: |
          python -c "import sys; print(sys.version)"
          ls
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install -e .[linters]
      - name: Running tests
        run: |
          make test
      - name: Isort
        run: |
          isort tghandler --check-only
      - name: Mypy
        run: |
          mypy tghandler/
      - name: Black
        run: |
          black tghandler/ --check
